# Generated by Django 5.2.14 on 2026-07-02 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_campaign_contactgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
