# Generated by Django 5.2.14 on 2026-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_delete_campaign_contact_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='groups', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
