# Generated by Django 5.2.14 on 2026-05-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='sms',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.smsmessage'),
        ),
    ]
