# Generated by Django 5.2.14 on 2026-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='message',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sender_id',
            field=models.CharField(max_length=50),
        ),
    ]
