# Generated by Django 5.2.14 on 2026-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_status'),
        ('contacts', '0003_delete_campaign_contact_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='contacts.contactgroup'),
        ),
    ]
